name: mobile
description: 'RPG game for mobile and web'
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: ^3.7.2

dependencies:
    cupertino_icons: ^1.0.8
    flutter:
        sdk: flutter
    flutter_dotenv: ^6.0.0
    flutter_launcher_icons: ^0.14.4
    flutter_secure_storage: ^9.2.4
    go_router: ^8.0.5
    http: ^1.5.0
    image_picker: ^1.2.0
    just_audio: ^0.9.42
    provider: ^6.1.5
    rxdart: ^0.28.0
    shared_preferences: ^2.0.15
    socket_io_client: ^3.1.2
    top_snackbar_flutter: ^3.1.0

dev_dependencies:
    build_runner: ^2.4.6
    flutter_test:
        sdk: flutter
    very_good_analysis: ^8.0.0

flutter_launcher_icons:
    android: true
    image_path: 'lib/assets/icons/android_icon.png'
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
    uses-material-design: true
    assets:
        - lib/assets/backgrounds/
        - lib/assets/theme/theme-light.json
        - lib/assets/main-menu/SteamSteel.png
        - lib/assets/characters/
        - lib/assets/icons/
        - lib/assets/profile/
        - lib/assets/previewcharacters/
        - lib/assets/pixelcharacters/
        - lib/assets/items/
        - lib/assets/tiles/
        - lib/assets/sounds/
        - lib/assets/banner/
        - lib/assets/level-badges/
        - lib/assets/profile/
        - .env

    fonts:
        - family: 'Press Start 2P'
          fonts:
              - asset: fonts/PressStart2P-Regular.ttf

        # An image asset can refer to one or more resolution-specific "variants", see
        # https://flutter.dev/to/resolution-aware-images

        # For details regarding adding assets from package dependencies, see
        # https://flutter.dev/to/asset-from-package

        # For details regarding fonts from package dependencies,
        # see https://flutter.dev/to/font-from-package
